### ISSUE TITLE
PAth Graphviz

### ISSUE THREAD

**Issue by gavenin** [glejeune/Leonhard#1]
Hello
I could not specify properly Path for Leonhard
(\Applications)
thank you for your help
regards

**Comment by glejeune** [comment]
What do you mean by "properly" ? What is exactly the problem ?

**Comment by gavenin** [comment]
Bonjour,
le logiciel me demande de reparamtrer via les prfrences le chemin d'accs
de Graphviz, situ dans le mme dossier application, hors en entrant
simplement le chemin d'accs,
/Volumes/Macintosh HD/applications
pas de succs
merci de votre aide

cordialement

2011/3/18 glejeune <
reply@reply.github.com>

**Comment by glejeune** [comment]
Hum... Leonhard needs the path to the graphviz binaries (dot, neato, ...) so, if you have installed GraphViz with the official package (from graphviz.org) try with /usr/local/bin.

**Comment by gavenin** [comment]
Works perfectly now
Thank you very much
I was looking for such kind of soft for some times

bests regards
Guillaume Avenin

**Comment by gavenin** [comment]
Hello
some feedback
1/ I have some conflict with textmate
2/ Issues with export functions
3/ I also experiment some regular crash 

what kind of information would you be interested in to help you?

regards

Guillaume Avenin

**Comment by glejeune** [comment]
Hi,

Everything ;) 

What do you mean by "conflict with textmate"?
Concerning the import issues, can you give me some examples?
Do you have logs about crashs?

Greg

**Comment by glejeune** [comment]
Please, create one issue per problem. 

Thanks.
